spring:
  application:
    name: ai-study-mate
  profiles:
    active: dev

# 공통 설정
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24시간

# OAuth2 설정 (환경별로 다름)
oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
